# Generated by Django 5.1.7 on 2024-04-25 09:10

from django.db import migrations

def add_initial_gift_cards(apps, schema_editor):
    GiftCard = apps.get_model('home', 'GiftCard')
    initial_cards = [
        {'code': 'SAVE50', 'value': 50, 'is_active': True},
        {'code': 'DISCOUNT100', 'value': 100, 'is_active': True},
        {'code': 'FLAT150', 'value': 150, 'is_active': True},
    ]
    for card_data in initial_cards:
        GiftCard.objects.get_or_create(code=card_data['code'], defaults=card_data)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_giftcard'),
    ]

    operations = [
        migrations.RunPython(add_initial_gift_cards),
    ]
